version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/kantibhuva
        ports:
            - "8082:80"
        links:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/kantibhuva
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        image: mysql:5.7
        build: ./docker/mysql
        ports:
            - "33061:3306"
        links:
            - phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
volumes:
    dbdata: