# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM nginx

ADD ./docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# VOLUME ./docker/nginx/logs:/var/log/nginx

EXPOSE 80
